/* 2. Import tailwind.ts variables to our theme - Gaply */
const spacing = {
  "-20": "-20px",
  "-16": "-16px",
  "-8": "-8px",
  "-4": "-4px",
  "-1": "-1px",
  "-05": "0.5px",
  "0": "0px",
  "1": "1px",
  "2": "2px",
  "4": "4px",
  "6": "6px",
  "8": "8px",
  "10": "10px",
  "12": "12px",
  "14": "14px",
  "16": "16px",
  "18": "18px",
  "20": "20px",
  "24": "24px",
  "28": "28px",
  "32": "32px",
  "36": "36px",
  "40": "40px",
  "44": "44px",
  "48": "48px",
  "56": "56px",
  "64": "64px",
  "72": "72px",
  "80": "80px",
  "96": "96px",
  "128": "128px",
  "192": "192px",
  "224": "224px",
  "256": "256px",
  "384": "384px",
  "576": "576px",
  "672": "672px",
  "1152": "1152px",
};

const theme = {
  colors: {
    background: {
      DEFAULT: "var(--base-white)",
      primary: {
        DEFAULT: "var(--grey-800)",
        hover: "var(--grey-900)",
        focus: "var(--grey-950)",
        inverse: "var(--base-white)",
        disabled: "var(--grey-500)",
      },
      secondary: {
        DEFAULT: "var(--grey-100)",
        hover: "var(--grey-200)",
        focus: "var(--grey-300)",
        inverse: "var(--grey-500)",
        disabled: "var(--grey-200)",
      },
      tertiary: {
        DEFAULT: "var(--grey-50)",
        hover: "var(--grey-100)",
      },
      accent: {
        blue: {
          DEFAULT: "var(--blue-800)",
          hover: "var(--blue-900)",
          focus: "var(--blue-950)",
          disabled: "var(--blue-950)",
          subtle: "var(--blue-100)",
        },
        green: {
          DEFAULT: "var(--green-800)",
          hover: "var(--green-900)",
          focus: "var(--green-950)",
          disabled: "var(--green-200)",
          subtle: "var(--green-100)",
        },
        orange: {
          DEFAULT: "var(--orange-800)",
          hover: "var(--orange-900)",
          focus: "var(--orange-950)",
          disabled: "var(--orange-200)",
          subtle: "var(--orange-100)",
        },
        yellow: {
          DEFAULT: "var(--yellow-800)",
          hover: "var(--yellow-900)",
          focus: "var(--yellow-950)",
          disabled: "var(--yellow-200)",
          subtle: "var(--yellow-100)",
        },
        purple: {
          DEFAULT: "var(--purple-800)",
          hover: "var(--purple-900)",
          focus: "var(--purple-950)",
          disabled: "var(--purple-200)",
          subtle: "var(--purple-100)",
        },
      },
      error: {
        DEFAULT: "var(--error-500)",
        hover: "var(--error-600)",
        focus: "var(--error-700)",
        disabled: "var(--error-200)",
        subtle: "var(--error-100)",
      },
    },
    text: {
      primary: {
        DEFAULT: "var(--base-black)",
        inverse: "var(--grey-50)",
      },
      secondary: {
        DEFAULT: "var(--grey-500)",
        hover: "var(--grey-600)",
        inverse: "var(--grey-300)",
        disabled: "var(--grey-200)",
      },
      tertiary: {
        DEFAULT: "var(--grey-400)",
        inverse: "var(--grey-100)",
      },
      accent: {
        blue: {
          DEFAULT: "var(--blue-700)",
          hover: "var(--blue-800)",
          focus: "var(--blue-900)",
          disabled: "var(--blue-200)",
          subtle: "var(--blue-50)",
        },
        green: {
          DEFAULT: "var(--green-700)",
          hover: "var(--green-800)",
          focus: "var(--green-900)",
          disabled: "var(--green-200)",
          subtle: "var(--green-50)",
        },
        orange: {
          DEFAULT: "var(--orange-700)",
          hover: "var(--orange-800)",
          focus: "var(--orange-900)",
          disabled: "var(--orange-200)",
          subtle: "var(--orange-50)",
        },
        yellow: {
          DEFAULT: "var(--yellow-700)",
          hover: "var(--yellow-800)",
          focus: "var(--yellow-900)",
          disabled: "var(--yellow-200)",
          subtle: "var(--yellow-50)",
        },
        purple: {
          DEFAULT: "var(--purple-700)",
          hover: "var(--purple-800)",
          focus: "var(--purple-900)",
          disabled: "var(--purple-200)",
          subtle: "var(--purple-100)",
        },
      },
      error: "var(--error-500)",
    },
    border: {
      mono: "var(--grey-700)",
      inverse: "var(--base-white)",
      primary: "var(--grey-300)",
      secondary: "var(--grey-200)",
      tertiary: "var(--grey-100)",
      disabled: "var(--grey-300)",
      error: "var(--error-500)",
      accent: {
        blue: {
          DEFAULT: "var(--blue-500)",
          subtle: "var(--blue-300)",
          hover: "var(--blue-600)",
          focus: "var(--blue-700)",
          disabled: "var(--blue-200)",
        },
        green: {
          DEFAULT: "var(--green-500)",
          subtle: "var(--green-300)",
          hover: "var(--green-600)",
          focus: "var(--green-700)",
          disabled: "var(--green-200)",
        },
        orange: {
          DEFAULT: "var(--orange-500)",
          subtle: "var(--orange-300)",
          hover: "var(--orange-600)",
          focus: "var(--orange-700)",
          disabled: "var(--orange-200)",
        },
        yellow: {
          DEFAULT: "var(--yellow-500)",
          subtle: "var(--yellow-300)",
          hover: "var(--yellow-600)",
          focus: "var(--yellow-700)",
          disabled: "var(--yellow-200)",
        },
        purple: {
          DEFAULT: "var(--purple-500)",
          subtle: "var(--purple-300)",
          hover: "var(--purple-600)",
          focus: "var(--purple-700)",
          disabled: "var(--purple-200)",
        },
      },
    },
    focusRing: {
      primary: "var(--grey-100)",
      accent: {
        blue: "var(--blue-100)",
        green: "var(--green-100)",
        orange: "var(--orange-100)",
        yellow: "var(--yellow-100)",
        purple: "var(--purple-100)",
        error: "var(--error-100)",
      },
    },
    chart: {
      primary: "var(--grey-100)",
      accent: {
        blue: "var(--blue-500)",
        green: "var(--green-500)",
        orange: "var(--orange-500)",
        yellow: "var(--yellow-500)",
        purple: "var(--purple-500)",
      },
    },
    icon: {
      primary: {
        mono: "var(--grey-400)",
        DEFAULT: "var(--base-black)",
        inverse: "var(--base-white)",
      },
      secondary: {
        DEFAULT: "var(--grey-500)",
        hover: "var(--grey-600)",
        inverse: "var(--grey-700)",
        disabled: "var(--grey-200)",
      },
      accent: {
        blue: {
          DEFAULT: "var(--blue-700)",
          hover: "var(--blue-800)",
          focus: "var(--blue-900)",
          disabled: "var(--blue-200)",
        },
        green: {
          DEFAULT: "var(--green-700)",
          hover: "var(--green-800)",
          focus: "var(--green-900)",
          disabled: "var(--green-200)",
        },
        orange: {
          DEFAULT: "var(--orange-700)",
          hover: "var(--orange-800)",
          focus: "var(--orange-900)",
          disabled: "var(--orange-200)",
        },
        yellow: {
          DEFAULT: "var(--yellow-500)",
          hover: "var(--yellow-600)",
          focus: "var(--yellow-700)",
          disabled: "var(--yellow-200)",
        },
        purple: {
          DEFAULT: "var(--purple-500)",
          hover: "var(--purple-600)",
          focus: "var(--purple-700)",
          disabled: "var(--purple-200)",
        },
      },
    },
  },
  fontSize: {
    8: spacing["8"],
    10: spacing["10"],
    12: spacing["12"],
    14: spacing["14"],
    16: spacing["16"],
    18: spacing["18"],
    20: spacing["20"],
    24: spacing["24"],
    32: spacing["32"],
    36: spacing["36"],
    48: spacing["48"],
    footnote: spacing["10"],
  },
  fontFamily: {
    DEFAULT: ["Graphik-Regular", "sans-serif"],
    graphik: ["Graphik-Regular", "sans-serif"],
    semibold: ["Graphik-Semibold", "sans-serif"],
    bold: ["Graphik-Bold", "sans-serif"],
  },
  fontWeight: {
    DEFAULT: 400,
    graphik: 400,
    semibold: 500,
    bold: 700,
  },
  border: {
    "05": spacing["-05"],
    1: spacing["1"],
    2: spacing["2"],
    4: spacing["4"],
    8: spacing["8"],
  },
  borderRadius: {
    DEFAULT: spacing["4"],
    none: spacing["0"],
    sm: spacing["2"],
    md: spacing["6"],
    lg: spacing["8"],
    xl: spacing["12"],
    "2xl": spacing["16"],
    "3xl": spacing["24"],
    "4xl": spacing["32"],
    full: "9999px",
  },
  lineHeight: {
    12: spacing["12"],
    16: spacing["16"],
    20: spacing["20"],
    24: spacing["24"],
    28: spacing["28"],
    32: spacing["32"],
    40: spacing["40"],
    44: spacing["44"],
    56: spacing["56"],
    72: spacing["72"],
    80: spacing["80"],
  },
  letterSpacing: {
    0: "0px",
    "02": "-0.20000000298023224px",
    "055": "-0.550000011920929px",
    18: "-1.7999999523162842px",
  },
  maxWidth: {
    "short-length-sm": spacing["384"],
    "long-length-sm": spacing["576"],
    "short-length-lg": spacing["672"],
    "long-length-lg": spacing["1152"],
  },
  minHeight: {
    "screen-offset": "calc(100dvh - 80px)",
  },
  customProperties: {},
};

module.exports.themecolors = theme.colors;
// module.exports.themespacing = theme.spacing;
module.exports.themecustomProperties = theme.customProperties;
module.exports.themefontSize = theme.fontSize;
module.exports.themefontFamily = theme.fontFamily;
module.exports.themefontWeight = theme.fontWeight;
module.exports.themeborderRadius = theme.borderRadius;
module.exports.themelineHeight = theme.lineHeight;
module.exports.thememaxWidth = theme.maxWidth;
module.exports.thememinHeight = theme.minHeight;
module.exports.themeletterSpacing = theme.letterSpacing;
